python3 run_for_val.py \
    --batch_size 4 \
    --port 1234 \
    --dist False \
    --seed 21 \
    --model_type vit_b \
    --checkpoint sam_vit_b.pth \
    --epoch 1 \
    --lr 2e-4 \
    --pth_name weight_for_valid \
    --project_name valid_test\